# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "Gecko Inventory"
  port = 8910
  apiUrl = "/.redwood/functions"
  includeEnvironmentVariables = [
    'CLERK_PUBLISHABLE_KEY',
    'CLERK_FRONTEND_API_URL'
  ]
[api]
  port = 8911
  includeEnvironmentVariables = [
    'CLERK_SECRET_KEY'
  ]
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]
